# The node-{composition,env,packages}.nix files were generated by the following:
# nix shell nixpkgs#node2nix --command node2nix \
#   --nodejs-14 --input package.json \
#   --composition node-composition.nix

{
  pkgs,
  node-pre-gyp,
  lib,
  fetchFromGitHub,
  nodejs,
  sqlite,
  ...
}: let
  nodePackages = pkgs.callPackage ./node-composition.nix {};
in nodePackages.package.override {
  version = "2.0.0";
  src = fetchFromGitHub {
    owner = "clusterzx";
    repo = "paperless-ai";
    rev = "3050abe7670e7e49ff728eedbffafb6da37706fe";
    hash = "sha256-mgj3+Wj0WorK1obBo7iYREsZc27wzS2Gnw5xVYn7fDw=";
  };
  postInstall = ''
    mkdir -p $out/bin

    cat <<EOF > $out/bin/paperless-ai
    #!/bin/sh
    exec ${lib.getExe nodejs} $out/lib/node_modules/paperless-ai/server.js "\$@"
    EOF
    chmod +x $out/bin/paperless-ai
  '';
}
