# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: WakaTime.WakaTime
PackageVersion: 1.0.1
PackageLocale: en-US
Publisher: WakaTime
PackageName: WakaTime
License: BSD-3-Clause License
Copyright: Copyright © 2024 Wakatime
ShortDescription: WakaTime desktop system tray app.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
