
on:
  workflow_dispatch: ~
  push: ~

jobs:
  build-pwn:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          # - ubuntu-22.04
          # - ubuntu-24.04-arm
          # - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    # permissions:
    #   id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install generic dependencies
        run: |
          sudo apt install -y build-essential dpkg-dev devscripts

        # python3-file-read-backwards was added in Ubuntu 24.10
      - name: Download and extract python3-file-read-backwards sources
        run: |
          mkdir -p ./Debian/pkgs/_build
          pushd ./Debian/pkgs/_build || exit 1
          base="http://archive.ubuntu.com/ubuntu/pool/universe/f/file-read-backwards/file-read-backwards_3.1.0"
          wget "$base-2.dsc"
          wget "$base.orig.tar.gz"
          wget "$base-2.debian.tar.xz"
          dpkg-source -x file-read-backwards_3.1.0-2.dsc
          popd
      - name: Build python3-file-read-backwards
        run: |
          pushd ./Debian/pkgs/_build/file-read-backwards-3.1.0 || exit 1
          dpkg-buildpackage -us -uc
          popd
      - name: Install python3-file-read-backwards
        run: |
          sudo apt install -y ./Debian/pkgs/_build/file-read-backwards_3.1.0-2_all.deb

      - name: Install gorm-paginator dependencies
        run: |
          sudo apt build-dep -y ./Debian/pkgs/golang-github-biezhi-gorm-paginator
      - name: Build gorm-paginator
        run: |
          pushd Debian/pkgs || exit 1
          ./build.sh golang-github-biezhi-gorm-paginator
          ls _build
          popd
      - name: Install gorm-paginator
        run: |
          sudo apt install -y ./Debian/pkgs/_build/golang-github-biezhi-gorm-paginator-dev_*.deb

      - name: Install pwngrid dependencies
        run: |
          sudo apt build-dep -y ./Debian/pkgs/pwngrid
      - name: Build pwngrid
        run: |
          cd Debian/pkgs || exit 1
          ./build.sh pwngrid
          ls _build
          cd ../..
      - name: Install pwngrid
        run: |
          sudo apt install -y ./Debian/pkgs/_build/pwngrid_*.deb

      - name: Install pwnagotchi dependencies
        run: |
          sudo apt build-dep -y ./Debian/pkgs/pwnagotchi
      - name: Build pwnagotchi
        run: |
          cd Debian/pkgs || exit 1
          ./build.sh pwnagotchi
          ls _build
          cd ../..
      - name: Install pwnagotchi
        run: |
          sudo apt install -y ./Debian/pkgs/_build/pwnagotchi_*.deb

      # - uses: sigstore/gh-action-sigstore-python@v3.0.0
      #   with:
      #     inputs: ./Debian/pkgs/_build/*/*.deb

      - uses: actions/upload-artifact@v4
        with:
          name: Packaging outputs for ${{ matrix.os }}
          path: |
            Debian/pkgs/_build/*.deb
            Debian/pkgs/_build/*.buildinfo
            Debian/pkgs/_build/*.dsc
            Debian/pkgs/_build/*.changes
  
  build-cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: skyenet
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build mlton
        run: |
          nix build ./NixOS#mlton
      - name: Build Porkbun-DDNS
        run: |
          nix build ./NixOS#porkbun-ddns
      - name: Build anemoi
        run: |
          nix build ./NixOS#anemoi
