
on: workflow_dispatch

jobs:
  build-gorm-paginator:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install -y build-essential dpkg-dev devscripts
          sudo apt build-dep -y ./Debian/pkgs/golang-github-biezhi-gorm-paginator
      - name: Build gorm-paginator
        run: |
          cd Debian/pkgs || exit 1
          ./build.sh golang-github-biezhi-gorm-paginator
          ls _build
          cd ../..
      # - uses: sigstore/gh-action-sigstore-python@v3.0.0
      #   with:
      #     inputs: ./Debian/pkgs/_build/*/*.deb
      - uses: actions/upload-artifact@v4
        with:
          name: Deb file
          path: |
            Debian/pkgs/_build/*.deb
            Debian/pkgs/_build/*.buildinfo
            Debian/pkgs/_build/*.dsc
            Debian/pkgs/_build/*.changes
